item{
    id: 1
    name: 'blow-horn'
    }
    item{
    id: 2
    name: 'green Light'
    }
item{
    id: 3
    name: 'Go Stright'
    }
item{
    id: 4
    name: 'keep-left'
    }
item{
    id: 5
    name: 'no-horn'
    }
item{
    id: 6
    name: 'red-light'
    }
item{
    id: 7
    name: 'speed-50'
    }
item{
    id: 8
    name: 'Stop'
    }
item{
    id: 9
    name: 'u-turn'
    }
item{
    id: 10
    name: 'yellow-light'    
    }